plugins {
    id 'com.android.application'
}

android {
    namespace 'com.apusengine.toolchain'
    compileSdk 36
    buildToolsVersion '36.0.0'
    ndkVersion '27.3.13750724'

    defaultConfig {
        applicationId 'com.apusengine.toolchain'
        minSdk 21
        targetSdk 36
        versionCode 1
        versionName '0.1'

        externalNativeBuild {
            ndkBuild {
                arguments 'APP_PLATFORM=android-21'
                abiFilters 'arm64-v8a'
            }
        }
    }

    externalNativeBuild {
        ndkBuild {
            path 'jni/Android.mk'
        }
    }

    sourceSets.main {
        jniLibs.srcDir 'libs'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
