# This is a basic workflow to help you get started with Actions

name: Build-Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the engine4 branch
  push:
    branches: [ engine4 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Lazarus environment
      # You may pin to the exact commit or the version.
      # uses: gcarreno/setup-lazarus@815641b356c1e4e0e68795d237fb13e89484e25b
      uses: gcarreno/setup-lazarus@v3.2
      with:
        lazarus-version: stable
    - run: pwd
    - name: Compile TestMyServis
      run: lazbuild -q -q Base/tests/TestMyServis.lpi
    - name: Compile TestMath
      run: lazbuild -q -q Base/tests/TestMath.lpi
    - name: Compile TestStructs
      run: lazbuild -q -q Base/tests/TestStructs.lpi
    - name: Compile TestGFX
      run: lazbuild -q -q Base/tests/TestGFX.lpi
    - run: Base/tests/TestMyServis-fpc
    - run: Base/tests/TestMath
    - run: Base/tests/TestStructs
    - run: Base/tests/TestGFX

    - name: Compile SimpleDemo
      run: lazbuild -q -q demo/SimpleDemo/SimpleDemo.lpi
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: saved_output
        path: demo/SimpleDemo/
    - name: Compile Scenes
      run: lazbuild -q -q demo/01-Scenes/scenes.lpi
    - name: Compile NinePatch
      run: lazbuild -q -q demo/NinePatch/NinePatch.lpi
    - name: Compile Simple3D
      run: lazbuild -q -q demo/Simple3D/Simple3D.lpi
    - name: Compile AdvTex
      run: lazbuild -q -q demo/AdvTex/AdvTex.lpi
    - name: Compile ControllerDemo
      run: lazbuild -q -q demo/ControllerDemo/ControllerDemo.lpi
    - name: Compile ShadowMap
      run: lazbuild -q -q demo/ShadowMap/ShadowMap.lpi
    - name: Compile SoundDemo
      run: lazbuild -q -q demo/SoundDemo/soundDemo.lpi


  test-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest
    timeout-minutes: 15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Lazarus environment
      # You may pin to the exact commit or the version.
      # uses: gcarreno/setup-lazarus@815641b356c1e4e0e68795d237fb13e89484e25b
      uses: gcarreno/setup-lazarus@v3.2
      with:
        lazarus-version: stable
    - run: pwd
    - name: Compile TestMyServis
      run: lazbuild -q -q Base/tests/TestMyServis.lpi
    - name: Compile TestMath
      run: lazbuild -q -q Base/tests/TestMath.lpi
    - name: Compile TestStructs
      run: lazbuild -q -q Base/tests/TestStructs.lpi
    - name: Compile TestGFX
      run: lazbuild -q -q Base/tests/TestGFX.lpi
    - run: dir Base/tests
    - run: Base/tests/TestMyServis-fpc
    - run: Base/tests/TestMath
    - run: Base/tests/TestStructs
    - run: Base/tests/TestGFX

    - name: Compile SimpleDemo
      run: lazbuild -q -q demo/SimpleDemo/SimpleDemo.lpi
    - name: Compile Scenes
      run: lazbuild -q -q demo/01-Scenes/scenes.lpi
    - name: Compile NinePatch
      run: lazbuild -q -q demo/NinePatch/NinePatch.lpi
    - name: Compile Simple3D
      run: lazbuild -q -q demo/Simple3D/Simple3D.lpi
    - name: Compile AdvTex
      run: lazbuild -q -q demo/AdvTex/AdvTex.lpi      
    - name: Compile ControllerDemo
      run: lazbuild -q -q demo/ControllerDemo/ControllerDemo.lpi
    - name: Compile ShadowMap
      run: lazbuild -q -q demo/ShadowMap/ShadowMap.lpi
    - name: Compile SoundDemo
      run: lazbuild -q -q demo/SoundDemo/soundDemo.lpi

